### PR TITLE
fixes mobz/elasticsearch-head#270

### PR DESCRIPTION
**Pull request by cyberhck**

### CODE REVIEW

**Comment by philipskokoh** [comment]
You set the max-height to fix number. If the search query returns large number of document, the height will be max 200px.

**Comment by cyberhck** [comment]
I get we can close this PR?

**Comment by mobz** [comment]
I'm a bit confused about this pull request. For a start, you need to change the code in the src directory, and use the build tools to build the _site folder. But would setting the max-height of the uiTable-body mean that the height does not grow larger than 200px? What if your browser window is larger?

**Comment by cyberhck** [comment]
Thanks, I'm not very good with CSS or vanilla.js (I'll have a look into this a little later)

**Comment by cyberhck** [comment]
closing this, as I don't use elastic search for now, will come back later if issue still exists.

**Pull request closed without merging**
