### PR TITLE
[fix]解决x-pack问题

### PR DESCRIPTION
**Pull request by zhaoyunxing92**
elasticsearch opens x-pack after connection fails，I have set it according to the document `http://localhost:9100/?auth_user=elastic&auth_password=changeme` 
I want to know what frame you're using on the front end so I can get to it faster

### CODE REVIEW

**Comment by zhaoyunxing92** [comment]
elasticsearch opens x-pack after connection fails，I have set it according to the document http://localhost:9100/?auth_user=elastic&auth_password=changeme
I want to know what frame you're using on the front end so I can get to it faster

**Comment by philipskokoh** [comment]
Sorry, I do not quite follow the issue. Is this specifically only for chrome extension or also for standalone server?

Please do not modify `app.js` directly. This file is automatically generated by grunt. See https://github.com/mobz/elasticsearch-head#contributing for more details.

The file that you currently modify is 
https://github.com/mobz/elasticsearch-head/blob/bee08506a964c1bff32c7be9c0b219a728f2704d/src/app/ui/clusterConnect/clusterConnect.js

**Comment by zhaoyunxing92** [comment]
Sorry, I didn't see the code for `http://localhost:9200/?auth_user=elastic&auth_password=changeme` support, I have modified it in app.js, there is this question in both chrome plugin and docker version
I can resubmit

**Comment by philipskokoh** [comment]
Hi @zhaoyunxing92,
For Chrome plugin, it's better to send the pull request on elasticsearch-head-chrome repo:
https://github.com/TravisTX/elasticsearch-head-chrome

This repo does not have chrome plugins codes.

**Comment by zhaoyunxing92** [comment]
The code itself is also problematic. It is not successful to enter the account password in the format directly because the username and password are not resolved

**Comment by philipskokoh** [comment]
Sorry I do not really understand chrome plugin code. Could you tell me on how to test this code?

**Comment by zhaoyunxing92** [comment]
You may not understand what I said, what I mean is that the code itself has bugs and is made into docker, google plugin, google plugin problem I also submitted the problem, you can `npm run start` and test it with x-pack on open

**Comment by philipskokoh** [comment]
You are right. There is an issue at connect button. I don't realize this issue because I rarely use it. I normally connect to cluster directly via browser URL or using local proxy (and both methods are working fine). 
Thanks for the fix! And also the chrome extension. Sorry for long delay.
After merging this PR, I will re-organize your code (especially your chrome extension part under `_site`). `_site` folder is always cleared everytime, we build the source.

**Comment by philipskokoh** [comment]
fixed a small bug on parsing auth parameters. I also updated the crx file.

**Pull request merged**
