### PR TITLE
Fix ES2.0 breaking errors

### PR DESCRIPTION
**Pull request by philipskokoh**
Few updates to resolve breaking errors in elasticsearch-head

Update quick menu on header UI:
* fix api path for cluster nodes, node stats and plugins
* change labels to follow elasticsearch terms in elasticsearch documentation. Please help update the texts in other languages.
 * Status --> Indices Stats
 * Node Stats --> Nodes Stats
 * Cluster Nodes --> Nodes Info

Update Indices Overview tab:
* fix errors in reading new response format from ES2.0

Update Structured Query tab:
* use `/_stats` instead of `/_status`. `/_status` is not working anymore in ES2.0.
* Facet is removed. Currently, I just remarked the code. I plan to include aggregation later.
* Type name prefix removed in elasticsearch 2.0. When executing query, first segment of the field name (before the first dot) is removed from structuredQuery.
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_mapping_changes.html#_type_name_prefix_removed

### CODE REVIEW

**Comment by mobz** [comment]
Hi thanks for this commit, I will make some time to review it asap

**Comment by philipskokoh** [comment]
I made more changes in this branch.

Structured Query tab:
* fix boolean issue #210 by adding term ops for boolean type
* remove deprecated option 'from', 'to' from range filter. Reference: https://www.elastic.co/guide/en/elasticsearch/reference/0.90/query-dsl-range-filter.html

**Comment by philipskokoh** [comment]
Index Overview:
* fix size and docs values in indices overview. First part showing numbers from primary nodes, second part (inside bracket) showing all numbers including replicas.

**Comment by philipskokoh** [comment]
Added Browser tab updates:
* use full path for filter fields
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_fields_cannot_be_referenced_by_short_name
* added short, byte in coretype_map
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-types.html

**Comment by philipskokoh** [comment]
More updates on this branch. This commit modifies facets to aggregations.

Details:
* Change facet to aggregation in `query.js`
* Change text 'Loading  Facets' to 'Loading Aggregations'. Please help to update the translation.
* Browser tab:
 * Update DateHistogram to use Aggregation

**Comment by kamelia78** [comment]
Hi,
I'm facing the same problem, how can I solve it ?
Thank you!
Kamélia.

**Comment by philipskokoh** [comment]
Added new commit to solve csv issue on large hits. This commit should solve #224. 
Reference: 
http://stackoverflow.com/questions/23301467/javascript-exporting-large-text-csv-file-crashes-google-chrome

**Comment by awdng** [comment]
+1 for merging this

**Comment by ramandv** [comment]
+1

**Comment by edmorley** [comment]
When using current master (where this PR has just merged), the browser tab no longer loads, and the console shows:
```
00:01:55.240 String.prototype.contains() is deprecated and will be removed in a future release; use String.prototype.includes() instead index.html:15:8
00:01:57.700 Object { XHR Error: "error", message: "Bad Request" } app.js:1277:7
00:02:00.091 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. vendor.js:3074:28
00:02:25.850 POST 
XHR 
http://localhost:9200/bugs/_search [HTTP/1.1 400 Bad Request 358ms]
00:02:26.210 Object { XHR Error: "error", message: "Bad Request" }
```
Reverting my local checkout of this repo to 5b200a0 fixes the issue.

**Comment by arinto** [comment]
I tried to reproduce @edmorley 's issue on Firefox 38.5 on Centos6, connecting to Elasticsearch 2.0.0. 
The browser tab successfully loads and I could not replicate the issue.
May I know what is your Elasticsearch version and Firefox version?

**Comment by georgijd** [comment]
+1 for merging it :)

**Comment by edmorley** [comment]
> May I know what is your Elasticsearch version and Firefox version?

I've broken this out to #228.

**Pull request merged**
