### PR TITLE
add confirm when execute DELETE

### PR DESCRIPTION
**Pull request by haochun**
add confrim when execure DELETE.i think the DELTE method is a danger operate

### CODE REVIEW

**Comment by haochun** [comment]
i only add the zh_strings and en_strings i18n.I don't know how to other languages

**Comment by mobz** [comment]
This change has been considered before and is not a feature we want to add. Thanks for you pull request though.

**Comment by haochun** [comment]
Why is this feature don't want to add?i am delete data few minutes before by delete in head.because i am not careful.so,i think we should add this feature.i only confrim when the method is DELTE

**Comment by mobz** [comment]
It was a balance between people who need to use DELETE a lot, and it is designed to mimic the behaviour of `curl` which does not confirm DELETE operations either

**Comment by haochun** [comment]
user execute curl shell by write,we can care.but,when i use head delete data once.when i open the browser next time.the head will rember last operate.if we does not care the DELETE,i will request by match_all or other query.

**Pull request closed without merging**
