### PR TITLE
add dockerfile using node:alpine

### PR DESCRIPTION
**Pull request by shadiakiki1986**
The existing docker image on docker hub is 300 MB. Using node:alpine and the included dockerfile here, the image is down to 54 MB. I tried to figure out how to publish this on docker hub in parallel with the existing dockerfile, but it seems it requires putting the dockerfile in a separate folder, and then entering the folder name in the build settings on docker hub.

### CODE REVIEW

**Comment by mobz** [comment]
What is the purpose of using grunt-http-server rather than grunt-contrib-connect?

afaik they are both adequate static file servers I'm not sure what the benefit is, if we also need a whole new grunt file and the added complexity of having two quite different Dockerfiles, where the only practical difference is alpine/default.

**Comment by shadiakiki1986** [comment]
The 2nd gruntfile using grunt-http-server has less dependencies to install because it just uses the already-generated contents in the `_site` folder

**Comment by mobz** [comment]
ok, I see, perhaps don't bother using grunt at all. All you really need is a small http server, since you have node already, http-server is pretty good option (2.3Mb)

remove Gruntfile-alpine
in the Dockerfile-alpine;

- remove all `RUN npm install ...`
- add `RUN npm install http-server`
- change `CMD node_modules/http-server/bin/http-server _site -p 9100`

**Comment by shadiakiki1986** [comment]
That's a much better idea. I just pushed my commit, and now the image is ~60MB (down from ~100MB).
I didn't use `install -g` though (probably was an edit after I had committed?)

**Comment by mobz** [comment]
I'll try to publish to docker hub tomorrow, see how I go

**Comment by mobz** [comment]
published to https://hub.docker.com/r/mobz/elasticsearch-head

**Comment by philipskokoh** [comment]
wanna publish latest version to docker hub? I think latest updates should cover ES 6.x and 7.x.

**Pull request merged**
