### PR TITLE
Elasticsearch-2.0 refactoring

### PR DESCRIPTION
**Pull request by hmalphettes**
This refactoring is the minimum for displaying the cluster page with ES-2.0.0-beta1.
I have not tested further.
I hope this helps!

### CODE REVIEW

**Comment by mobz** [comment]
Thanks for this pull request - I'm correct in assuming `Bear minimum for shards status to render` will break the site for non-2.0 users?

**Comment by hmalphettes** [comment]
@mobz I just tested this against 1.7.1.
It installs fine. It reaches the same point than for 2.0.

2.0 has removed the "_status" query that has been deprecated since 1.2: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-status.html

Once we replace it with newer API we should be backward compatible down to ES-1.2.

**Comment by hmalphettes** [comment]
@mobz I reverted the commit that breaks ES<2.0 and is not enough for 2.0 anyways.

As far as I know everything works fine on ES-1.7.2 with these changes.

**Comment by NeckBeardPrince** [comment]
Any update on this?

**Comment by bingxie** [comment]
+1 wait for updating.

**Comment by pravink** [comment]
waiting for this fix..

**Comment by pravink** [comment]
i am trying to install kafka river pluing in 2.0 but it failed - 

-> Installing from file:/users/home/xbbll6c/servers/data/elasticsearch-river-kafka-1.3.0-SNAPSHOT-plugin.zip...
Trying file:/users/home/xbbll6c/servers/data/elasticsearch-river-kafka-1.3.0-SNAPSHOT-plugin.zip ...
Downloading ........................................................................................................................................................................................................................DONE
Verifying file:/users/home/xbbll6c/servers/data/elasticsearch-river-kafka-1.3.0-SNAPSHOT-plugin.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
bash-4.1$

**Comment by hodgezappa** [comment]
I've just got Elastic 2.2.1 running (on windows) but can't get the standalone head site working, any ideas??

**Comment by pravink** [comment]
below command should install head plugin -
$elasticsearch/bin/plugin install mobz/elasticsearch-head

Tried same and its working in my case.

**Comment by hodgezappa** [comment]
Hi Pravink, yep that worked for me too, i'm wondering why the stand alone version doesn't work, what is it about the plugin that makes it work I wonder?

**Pull request merged**
