### PR TITLE
Use node:alpine as a Base Image 

### PR DESCRIPTION
**Pull request by BigYopy**

### CODE REVIEW

**Comment by mobz** [comment]
@code0x9 can you comment, I'm not sure shat the difference is.

**Comment by mobz** [comment]
For my purposes I'm planning some new features that will require node 6 LTS or greater. So if that can be specified so much the better.

**Comment by code0x9** [comment]
@mobz
alpine linux(https://alpinelinux.org/about/) is basically small OS built around libc and busybox.
if elasticsearch-head docker image is based on alpine linux, users download much smaller image and official node build(https://hub.docker.com/_/node/) highly recommends alpine build.

```
node                       slim                58d21b88b8de        4 days ago          215.5 MB
node                       alpine              356564976a67        4 days ago          55.22 MB
node                       latest              7c4d899628d5        4 days ago          660.4 MB
```

> node:<version>
> This is the defacto image. If you are unsure about what your needs are, you probably want to use this one. It is designed to be used both as a throw away container (mount your source code and start the container to start your app), as well as the base to build other images off of. This tag is based off of buildpack-deps. buildpack-deps is designed for the average user of docker who has many images on their system. It, by design, has a large number of extremely common Debian packages. This reduces the number of packages that images that derive from it need to install, thus reducing the overall size of all images on your system.

> node:alpine
> This image is based on the popular Alpine Linux project, available in the alpine official image. Alpine Linux is much smaller than most distribution base images (~5MB), and thus leads to much slimmer images in general.
>
> This variant is highly recommended when final image size being as small as possible is desired. The main caveat to note is that it does use musl libc instead of glibc and friends, so certain software might run into issues depending on the depth of their libc requirements. However, most software doesn't have an issue with this, so this variant is usually a very safe choice. See this Hacker News comment thread for more discussion of the issues that might arise and some pro/con comparisons of using Alpine-based images.
>
> To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the alpine image description for examples of how to install packages if you are unfamiliar).

you can read about differences on https://hub.docker.com/_/node/. :)

p.s. current node image without version number(latest) is 7.4.

**Comment by mobz** [comment]
I think leaving the default node FROM basebox is ok for now, however perhaps if the basebox could be parameterised somehow? I'd be happy to publish :5-alpine as well

**Pull request closed without merging**
